version: '3.8'

networks:
  default:
    driver: bridge
  payment-processor:
    external: true

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rinha
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
        - default
    deploy:
      resources:
        limits:
          cpus:   '0.50'
          memory: '512M'

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
        - default
    deploy:
      resources:
        limits:
          cpus:   '0.25'
          memory: '256M'


  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-backend-api:latest
    entrypoint:
      - node
      - dist/main.js
    environment:
      PORT:               9999
      HOST:               0.0.0.0
      DATABASE_URL:       postgresql://user:pass@postgres:5432/rinha
      REDIS_URL:          redis://redis:6379
      PROCESSOR_DEFAULT:  http://host.docker.internal:8001
      PROCESSOR_FALLBACK: http://host.docker.internal:8002
    depends_on:
      - postgres
      - redis
    expose:
      - "9999"
    networks:
      - default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus:   '0.50'
          memory: '256M'

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-backend-worker:latest
    entrypoint:
      - node
      - --max-old-space-size=512
      - dist/queue/worker.js
    environment:
      DATABASE_URL:       postgresql://user:pass@postgres:5432/rinha
      REDIS_URL:          redis://redis:6379
      PROCESSOR_DEFAULT:  http://host.docker.internal:8001
      PROCESSOR_FALLBACK: http://host.docker.internal:8002
    depends_on:
      - api
      - redis
      - postgres
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus:   '0.50'
          memory: '256M'

  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus:   '0.25'
          memory: '128M'

volumes:
  postgres-data:
  redis-data:

