import { db } from "./connection";

async function migrate() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS payments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        correlation_id VARCHAR(255) NOT NULL,
        amount NUMERIC(12,2) NOT NULL,
        requested_at TIMESTAMPTZ NOT NULL,
        processed_at TIMESTAMPTZ,
        provider VARCHAR(100) NOT NULL
    );
  `);
}

if (Boolean(process.env.RUN_MIGRATIONS)) {
  console.log("Running migrations...");
  migrate().catch(console.error);
}
